<?php

/**
 * @file
 *  Installation/Un-installation hooks for CiviCRM Entity.
 */

/**
 *  Implements hook_uninstall()
 *
 */
function civicrm_entity_uninstall() {
  backdrop_load('module', 'civicrm_entity');
  $civicrm_entity_info = civicrm_entity_get_supported_entity_info();
  foreach ($civicrm_entity_info as $entity_type => $info) {
    field_attach_delete_bundle($entity_type, $entity_type);
  }
}

/**
 * Implements hook_enable().
 *
 * Set weight higher than CiviCRM.
 *
 * @TODO Actually check what CiviCRM's weight should be.
 */
function civicrm_entity_enable() {
  db_query("UPDATE {system} SET weight = 110 WHERE name = 'civicrm_entity'");
}

/**
 * Implements hook_update_last_removed().
 */
function civicrm_entity_update_last_removed() {
  return 7202;
}

/**
 * Move settings from variables to config.
 */
function civicrm_entity_update_1000() {
  // Migrate variables to config.
  $config = config('civicrm_entity.settings');
  $config->set('admin_enabled_entities', update_variable_get('civicrm_entity_admin_enabled_entities', array()));
  $config->set('contact_label_format', update_variable_get('civicrm_entity_contact_label_format', 'legacy'));
  $config->save();

  // Delete variables.
  update_variable_del('civicrm_entity_admin_enabled_entities');
  update_variable_del('civicrm_entity_contact_label_format');
}
